### ISSUE TITLE
Add badges to repo

### ISSUE THREAD

**Issue by sasalatart** [open-sir/open-sir#25]
We can include badges to the README that specify different things, like for example the build status from CircleCI, the License (apart from specifying it as a separate MD file and at the end of the README) among other things.

Eventually, with a slack org, we could also add a badge pointing to it.

**Comment by jia200x** [comment]
I'm in for this!

**Comment by jia200x** [comment]
Are the rest ok with this?

**Comment by felipehuerta17** [comment]
@all-contributors please add @sasalatart for code, maintenance and infra

**Comment by sasalatart** [comment]
Added MIT, CircleCI and Black badges.

In another PR, once the features are ready, I will add `pypi`, `docs` and "python versions" badges

**Comment by jia200x** [comment]
Thanks!
Since #48 got merged, shall we close the issue as resolved?

**Comment by jia200x** [comment]
@felipehuerta17 did you accidentally reopen the issue or is it intended?

**Comment by sasalatart** [comment]
I think we can close this issue for now
