### ISSUE TITLE
pip install . doesn't work in windows owing to read() function

### ISSUE THREAD

**Issue by felipehuerta17** [open-sir/open-sir#44]
**Describe the bug**
The packaging introduced in #33 yields the following error message in both cmd and powershell:

```
                                          ERROR: Command errored outib\encodings\cp1252.py", line 23, in decode with exit status 1:                                                e)[0]
     command: 'C:\Users\Felipe\.virtualenvs\open-sir-YJAL91ux\Scriptsition 5189: character maps to <undefined>s\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Felipe\\AppData\\Local\\Temp\\pip-req-build-hrl5ydwi\\nfo Check the logs for full command output.setup.py'"'"'; __file__='"'"'C:\\Users\\Felipe\\AppData\\Local\\Temp\\pip-req-build-hrl5ydwi\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Felipe\AppData\Local\Temp\pip-req-build-hrl5ydwi\pip-egg-info'
         cwd: C:\Users\Felipe\AppData\Local\Temp\pip-req-build-hrl5ydwi\
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Felipe\AppData\Local\Temp\pip-req-build-hrl5ydwi\setup.py", line 30, in <module>
        long_description=read('README.md'),
      File "C:\Users\Felipe\AppData\Local\Temp\pip-req-build-hrl5ydwi\setup.py", line 9, in read
        return open(os.path.join(os.path.dirname(__file__), fname)).read()
      File "C:\Users\Felipe\AppData\Local\Programs\Python\Python37\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 5189: character maps to <undefined>
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**To Reproduce**
1. Clone open-sir
2. Open a virtual-env and execute pip install .
3. See error

**Expected behavior**
The expected behavior would have been a clean successful installation of open-sir in Windows architecture

**Screenshots**

CMD shell within Visual Studio Code inside pipenv shell.

![image](https://user-images.githubusercontent.com/33637198/79041851-fae38580-7bea-11ea-9d63-c713f27ce877.png)

CMD shell inside conda environment
![image](https://user-images.githubusercontent.com/33637198/79041879-20708f00-7beb-11ea-98a4-55600a7dd450.png)

PS shell

![image](https://user-images.githubusercontent.com/33637198/79041945-9117ab80-7beb-11ea-8562-5dde9cb23996.png)

 - OS: Windows
 - Version 10

**Comment by felipehuerta17** [comment]
@jia200x I found the string that was causing the error:

![image](https://user-images.githubusercontent.com/33637198/79042114-e2746a80-7bec-11ea-9955-48eba8a31297.png)

I commented lines 8 and 9, and changed  the long description

![image](https://user-images.githubusercontent.com/33637198/79042120-ed2eff80-7bec-11ea-948f-3854cca9b23f.png)

And know pip install . ran, but throws a couple of errors on sklearn subdependencies:

![image](https://user-images.githubusercontent.com/33637198/79042136-118adc00-7bed-11ea-82cb-753b6fa0319d.png)

Did you experienced something similar?

**Comment by felipehuerta17** [comment]
An update:

1. The errors in red doesn't show if the user installed Anaconda, as all of those packages are there.
2. I just tested the setup *without the read function* in a new virtual environment created by conda and everything worked well.

**Comment by jia200x** [comment]
the problem is not the "read" function but the encoding of the README.md

To simplify this, we can simply add manually a long_description

**Comment by jia200x** [comment]
thanks for reporting the error!

**Comment by felipehuerta17** [comment]
In process of fixing: #52
