### ISSUE TITLE
SIR-X model has no tests

### ISSUE THREAD

**Issue by jia200x** [open-sir/open-sir#64]
So far the SIR-X model has no tests.
We should at least add some unittests to ensure all functions run without problems.

Ideally, we should also run some math tests (same as SIR).

Adding tests to SIR-X could be a good candidate for someone that wants to get used to the model and testing platform

**Comment by felipehuerta17** [comment]
I'll deal with this

![image](https://user-images.githubusercontent.com/33637198/79689151-d02ca900-824a-11ea-9495-770439943c51.png)

**Comment by jia200x** [comment]
Since https://github.com/open-sir/open-sir/pull/65 was already merged, we can close this one.

Tip: If one writes "Fixes #ISSUENUMBER in the PR (e.g "Fixes #65"), then Github automatically closes the issue.
